### ISSUE TITLE
[BUG REPORT]: 

### ISSUE THREAD

**Issue by MalinrRuwan** [TeamUltroid/Ultroid#132]
### Contact Details

@malinruwan

### What happened?

A bug happened!Traceback (most recent call last):

  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details

    return _get_module_details(pkg_main_name, error)

  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details

    __import__(pkg_name)

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/__init__.py", line 12, in <module>

    udB = redis_connection()

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/connections.py", line 100, in redis_connection

    our_db = connect_redis()

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/connections.py", line 86, in connect_redis

    return connect_qovery_redis()

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/connections.py", line 201, in connect_qovery_redis

    host=endpoint,

UnboundLocalError: local variable 'endpoint' referenced before assignment

### Version

0.0.8 (or later)

### Relevant logs output

```shell
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details

    return _get_module_details(pkg_main_name, error)

  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details

    __import__(pkg_name)

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/__init__.py", line 12, in <module>

    udB = redis_connection()

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/connections.py", line 100, in redis_connection

    our_db = connect_redis()

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/connections.py", line 86, in connect_redis

    return connect_qovery_redis()

  File "/usr/local/lib/python3.9/site-packages/pyUltroid/connections.py", line 201, in connect_qovery_redis

    host=endpoint,

UnboundLocalError: local variable 'endpoint' referenced before assignment
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by New-dev0** [comment]
Fill Env Variables

**Comment by amitkr-codes** [comment]
@MalinrRuwan Is it vps?

**Comment by MalinrRuwan** [comment]
Yes its a vps

**Comment by amitkr-codes** [comment]
@MalinrRuwan nano .env


Fill ur variables in that and save

Then 


python -m pyUltroid

**Comment by MalinrRuwan** [comment]
I ran it in a docker container by saving the env variables in .env file. But this is the result.

**Comment by amitkr-codes** [comment]
@MalinrRuwan Move .env file in /root/TeamUltroid

**Comment by MalinrRuwan** [comment]
I the container or in linux machine.

**Comment by xditya** [comment]
Please re-check if your `.env` file exists in the root of the cloned repository, then build the docker and run it.
