### ISSUE TITLE
[BUG REPORT] 

### ISSUE THREAD

**Issue by Kovinda** [TeamUltroid/Ultroid#158]
### Contact Details

swordartonline1109@protonmail.com

### What happened?

OSError: [Errno 28] No space left on device 

The assistant bot and the "My Ultroid Logs" group was created and the Assistant bot was added to the group.
Then this error occurred during deployment
deployed using railway.app

### Version

0.1

### Relevant logs output

```shell
09/14/2021, 20:32:11 || pyUltLog [INFO] - 
                -----------------------------------
                        Starting Deployment
                -----------------------------------

09/14/2021, 20:32:11 || pyUltLog [INFO] - py-Ultroid Version - 2021.9.13
09/14/2021, 20:32:11 || pyUltLog [INFO] - Telethon Version - 1.23.0
09/14/2021, 20:32:11 || pyUltLog [INFO] - Ultroid Version - 0.1
09/14/2021, 20:32:11 || pyUltLog [INFO] - Getting Connection With Redis Database
09/14/2021, 20:32:16 || pyUltLog [INFO] - Succesfully Established Connection With Redis DataBase.
09/14/2021, 20:32:18 || telethon.network.mtprotosender [INFO] - Connecting to 91.108.56.194:443/TcpFull...
09/14/2021, 20:32:18 || telethon.network.mtprotosender [INFO] - Connection to 91.108.56.194:443/TcpFull complete!
09/14/2021, 20:32:19 || pyUltLog [INFO] - MAKING A TELEGRAM BOT FOR YOU AT @BotFather, Kindly Wait
09/14/2021, 20:32:30 || pyUltLog [INFO] - DONE YOUR TELEGRAM BOT IS CREATED SUCCESSFULLY @kovinda_thisal_bot
09/14/2021, 20:32:30 || pyUltLog [INFO] - Initialising...
09/14/2021, 20:32:30 || pyUltLog [INFO] - Starting Ultroid...
09/14/2021, 20:32:30 || telethon.network.mtprotosender [INFO] - Connecting to 149.154.167.51:443/TcpFull...
09/14/2021, 20:32:32 || telethon.network.mtprotosender [INFO] - Connection to 149.154.167.51:443/TcpFull complete!
09/14/2021, 20:32:33 || telethon.client.users [INFO] - Phone migrated to 5
09/14/2021, 20:32:33 || telethon.client.telegrambaseclient [INFO] - Reconnecting to new data center 5
09/14/2021, 20:32:33 || telethon.network.mtprotosender [INFO] - Disconnecting from 149.154.167.51:443/TcpFull...
09/14/2021, 20:32:33 || telethon.network.mtprotosender [INFO] - Disconnection from 149.154.167.51:443/TcpFull complete!
09/14/2021, 20:32:33 || telethon.network.mtprotosender [INFO] - Connecting to 91.108.56.181:443/TcpFull...
09/14/2021, 20:32:35 || telethon.network.mtprotosender [INFO] - Connection to 91.108.56.181:443/TcpFull complete!
09/14/2021, 20:32:36 || pyUltLog [INFO] - Done, startup completed
09/14/2021, 20:32:36 || pyUltLog [INFO] - Assistant - Started
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/pyUltroid/__main__.py", line 88, in <module>
    ultroid_bot.loop.run_until_complete(autopilot())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/pyUltroid/startup/funcs.py", line 195, in autopilot
    urllib.request.urlretrieve(
  File "/usr/local/lib/python3.9/urllib/request.py", line 272, in urlretrieve
    tfp.write(block)
OSError: [Errno 28] No space left on device
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by amitkr-codes** [comment]
Don't know about this as you are the first user who reported this, [and maybe the last](https://t.me/UltroidSupport/701143)
