### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by mrflashcodex** [TeamUltroid/Ultroid#167]
### Contact Details

@ACCESS_HACKER

### What happened?

Traceback (most recent call last):
  File "/root/TeamUltroid/vcbot/__init__.py", line 229, in vc_handler
    await func(e)
  File "vcbot/videoplay.py", line 60, in video_c
    song, thumb, title, link, duration = await file_download(xx, reply)
  File "/root/TeamUltroid/vcbot/__init__.py", line 381, in file_download
    "vcbot/downloads/" + reply.file.name,
TypeError: can only concatenate str (not "NoneType") to str

### Version

0.0.8 (or later)

### Relevant logs output

```shell
Traceback (most recent call last):
  File "/root/TeamUltroid/vcbot/__init__.py", line 229, in vc_handler
    await func(e)
  File "vcbot/videoplay.py", line 60, in video_c
    song, thumb, title, link, duration = await file_download(xx, reply)
  File "/root/TeamUltroid/vcbot/__init__.py", line 381, in file_download
    "vcbot/downloads/" + reply.file.name,
TypeError: can only concatenate str (not "NoneType") to str
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by amitkr-codes** [comment]
Update has been pushed
