### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Fire7ly** [TeamUltroid/Ultroid#193]
### What happened?

Add pyUltroid.dB.database in  requirements.txt..
because railway don`t have this module occure each time of updation..
hope you try this..

Logs Here:-

### Version

0.0.8 (or later)

### Relevant logs output

```shell
10/13/2021, 15:33:51 || pyUltLogs [INFO] : • Installing Official's Plugins || Count : 85 •
10/13/2021, 15:33:59 || apscheduler.scheduler [INFO] : Adding job tentatively -- it will be properly scheduled when the scheduler starts
10/13/2021, 15:33:59 || apscheduler.scheduler [INFO] : Adding job tentatively -- it will be properly scheduled when the scheduler starts
10/13/2021, 15:33:59 || apscheduler.scheduler [INFO] : Added job "close_grp" to job store "default"
10/13/2021, 15:33:59 || apscheduler.scheduler [INFO] : Added job "open_grp" to job store "default"
10/13/2021, 15:33:59 || apscheduler.scheduler [INFO] : Scheduler started
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 21.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
10/13/2021, 15:34:08 || pyUltLogs [INFO] : • Installing Addons's Plugins || Count : 44 •
10/13/2021, 15:34:11 || pyUltLogs [INFO] : • Installing VCBot's Plugins || Count : 10 •
10/13/2021, 15:34:22 || pyUltLogs [INFO] : • Loading Plugins from Plugin Channel(s) •
10/13/2021, 15:34:22 || pyUltLogs [INFO] : •••• -480816525
10/13/2021, 15:34:29 || pyUltLogs [INFO] : Cmd('git') failed due to: exit code(128)
  cmdline: git remote add upstream https://github.com/TeamUltroid/Ultroid
  stderr: 'fatal: remote upstream already exists.'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/pyUltroid/__main__.py", line 68, in <module>
    cleanup_cache()
  File "/usr/local/lib/python3.9/site-packages/safety/tools/__init__.py", line 26, in cleanup_cache
    from pyUltroid.dB.database import Var
ModuleNotFoundError: No module named 'pyUltroid.dB.database'
```

### Acknowledgement

- [x] I have followed all of the above steps.

**Comment by New-dev0** [comment]
Update your local requirements
`pip3 install -r res*/sta*/op*`

**Comment by Fire7ly** [comment]
> Update your local requirements `pip3 install -r res*/sta*/op*`

cant on railway..

**Comment by 1Danish-00** [comment]
> > Update your local requirements `pip3 install -r res*/sta*/op*`
> 
> cant on railway..

redeploy then.
