### ISSUE TITLE
[BUG REPORT] Error while running 

### ISSUE THREAD

**Issue by WeakestHunter43** [TeamUltroid/Ultroid#220]
### What happened?

A bug happened!

### Version

0.0.8 (or later)

### Relevant logs output

```shell
_    _ _ _             _     _
 | |  | | | |           (_)   | |
 | |  | | | |_ _ __ ___  _  __| |
 | |  | | | __| '__/ _ \| |/ _  |
 | |__| | | |_| | | (_) | | (_| |
  \____/|_|\__|_|  \___/|_|\__,_|


Starting Ultroid...
This Package is Reserved By TeamUltroid..
11/25/2021, 12:26:42 || pyUltLogs [INFO] :
                -----------------------------------                                                             Starting Deployment
                -----------------------------------

11/25/2021, 12:26:42 || pyUltLogs [INFO] : py-Ultroid Version - 2021.10.11.1
11/25/2021, 12:26:42 || pyUltLogs [INFO] : Telethon Version - 1.23.0                    11/25/2021, 12:26:42 || pyUltLogs [INFO] : Ultroid Version - 0.2.1                      Traceback (most recent call last):                                                        File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main                      "__main__", mod_spec)                                                                 File "/usr/lib/python3.7/runpy.py", line 85, in _run_code                                 exec(code, run_globals)                                                               File "/usr/local/lib/python3.7/dist-packages/pyUltroid/__main__.py", line 14, in <module>
    from .startup.funcs import autopilot, customize, plug, ready, startup_stuff
  File "/usr/local/lib/python3.7/dist-packages/pyUltroid/startup/funcs.py", line 43
    if CT := udB.get("CUSTOM_THUMBNAIL"):
           ^
SyntaxError: invalid syntax
```

### Acknowledgement

- [ ] I have followed all of the above steps.

**Comment by New-dev0** [comment]
Make sure, you use Python version above than 3.7
