### ISSUE TITLE
v0.3 is not deploying

### ISSUE THREAD

**Issue by vedantmgoyal9** [TeamUltroid/Ultroid#244]
### Contact Details

@prophesur

### What happened?

v0.3 not deploying

### Version

0.3

### Hosted On

Vps

### Relevant logs output

```shell
12/31/2021, 18:56:34 || pyUltLogs [INFO] :
                -----------------------------------
                        Starting Deployment
                -----------------------------------

12/31/2021, 18:56:34 || pyUltLogs [INFO] : Python version - 3.9.7
12/31/2021, 18:56:34 || pyUltLogs [INFO] : py-Ultroid Version - 2022.01.01
12/31/2021, 18:56:34 || pyUltLogs [INFO] : Telethon Version - 1.25.0
12/31/2021, 18:56:34 || pyUltLogs [INFO] : Ultroid Version - 0.3
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/Ultroid/venv/lib/python3.9/site-packages/pyUltroid/__init__.py", line 15, in <module>
    from .startup.funcs import _version_changes, autobot
  File "/home/ubuntu/Ultroid/venv/lib/python3.9/site-packages/pyUltroid/startup/funcs.py", line 43, in <module>
    from ..functions.helper import download_file, updater
  File "/home/ubuntu/Ultroid/venv/lib/python3.9/site-packages/pyUltroid/functions/helper.py", line 17, in <module>
    from safety.tools import sys_exit
ImportError: cannot import name 'sys_exit' from 'safety.tools' (/home/ubuntu/Ultroid/venv/lib/python3.9/site-packages/safety/tools/__init__.py)
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by New-dev0** [comment]
You need to manually update requirements and optional requirements.
`pip3 install --no-cache-dir requirements.txt`
`pip3 install --no-cache-dir res*/st*/op*`

**Comment by vedantmgoyal9** [comment]
Oops, I forgot to update the dependencies, thanks for reminding me.

**Comment by vedantmgoyal9** [comment]
@New-dev0 Where is the SPAM plugin?

**Comment by New-dev0** [comment]
> @New-dev0 Where is the SPAM plugin?

Spam is a addons plugin, so it's available at https://GitHub.com/TeamUltroid/UltroidAddons

**Comment by vedantmgoyal9** [comment]
Was it inbuilt before?

**Comment by New-dev0** [comment]
@vedantmgoyal2009 Ok i got your issue.

In v0.3 Addons are set to False by default.
So you need to do .setdb ADDONS True to enable addons.

Same for Vc

**Comment by vedantmgoyal9** [comment]
Thanks :-)
