### ISSUE TITLE
[BUG REPORT] VC BOT

### ISSUE THREAD

**Issue by vedantmgoyal9** [TeamUltroid/Ultroid#247]
### What happened?

VC bot not working.

### Version

0.3

### Hosted On

Vps

### Relevant logs output

```shell
VC Error - 2022.01.01.1

.play believer

Traceback (most recent call last):
  File "/home/ubuntu/ultroid/vcbot/__init__.py", line 242, in vc_handler
    await func(e)
  File "/home/ubuntu/ultroid/vcbot/play.py", line 70, in play_music_
    await ultSongs.group_call.start_audio(song)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pytgcalls/implementation/group_call.py", line 187, in start_audio
    self._audio_stream = AudioStream(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/pytgcalls/utils.py", line 206, in __init__
    self.__input_container = av.open(source)
  File "av/container/core.pyx", line 355, in av.container.core.open
  File "av/container/core.pyx", line 226, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 258, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.FileNotFoundError: [Errno 2] No such file or directory
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by vedantmgoyal9** [comment]
@New-dev0 Any info about this one? I think I have set up everything correctly according to the documentation.

**Comment by amitkr-codes** [comment]
@vedantmgoyal2009 Error from pyav library, it doesn't work with link on vps, try replying to audio/video

**Comment by vedantmgoyal9** [comment]
Isn't there any way to fix it?

**Comment by 1Danish-00** [comment]
> Isn't there any way to fix it?

Check https://pyav.org/docs/stable/overview/installation.html
(make sure u installed all required dependencies)

then try
`pip3 uninstall av`
`pip3 install av --no-binary av`

**Comment by vedantmgoyal9** [comment]
I have done that, still, I can't play using `.play all is well` and the second issue is that playing by replying to an audio or video file plays the song successfully but the speed is too fast.

**Comment by vedantmgoyal9** [comment]
Any fix for this?

**Comment by amitkr-codes** [comment]
@vedantmgoyal2009 Forward that audio in t.me/ultroidspam which was playing fast
