### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by thekillpro30** [TeamUltroid/Ultroid#351]
### Contact Details

@jefersonbp2801

### What happened?

VCBOT not working

### Version

0.3

### Hosted On

Vps

### Relevant logs output

```shell
08/08/2022, 15:25:49 | pyUltLogs [ERROR] : pyUltroid - VCBot - ERROR - vcbot.ytplaylist
08/08/2022, 15:25:49 | pyUltLogs [ERROR] : cannot import name 'GroupCallFactory' from 'pytgcalls' (/home/thekillpro/.local/lib/python3.8/site-packages/pytgcalls/__init__.py)
Traceback (most recent call last):
  File "/home/thekillpro/.local/lib/python3.8/site-packages/pyUltroid/loader.py", line 53, in load
    modl = func(plugin)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/thekillpro/jhomar/Ultroid/vcbot/__init__.py", line 26, in <module>
    from pytgcalls import GroupCallFactory
ImportError: cannot import name 'GroupCallFactory' from 'pytgcalls' (/home/thekillpro/.local/lib/python3.8/site-packages/pytgcalls/__init__.py)

```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by New-dev0** [comment]
assuming you have either installed "py-tgcalls" or older version of pytgcalls.
Make sure, you install
`pytgcalls==3.0.0.dev21`
[#](https://github.com/TeamUltroid/Ultroid/blob/main/requirements.txt#L5)

Reopen if this doesn`t solve your issue.

**Comment by thekillpro30** [comment]
> assuming you have either installed "py-tgcalls" or older version of pytgcalls. Make sure, you install `pytgcalls==3.0.0.dev21` [#](https://github.com/TeamUltroid/Ultroid/blob/main/requirements.txt#L5)
> 
> Reopen if this doesn`t solve your issue.

Requirement already satisfied: numpy>=1.14.5 in ./.local/lib/python3.8/site-packages (from opencv-python-headless==4.5.5.62->pytgcalls==3.0.0.dev21) (1.23.1)

**Comment by thekillpro30** [comment]
> assuming you have either installed "py-tgcalls" or older version of pytgcalls. Make sure, you install `pytgcalls==3.0.0.dev21` [#](https://github.com/TeamUltroid/Ultroid/blob/main/requirements.txt#L5)
> 
> Reopen if this doesn`t solve your issue.

Requirement already satisfied: pytgcalls==3.0.0.dev21 in ./.local/lib/python3.8/site-packages (3.0.0.dev21)
