### ISSUE TITLE
[BUG REPORT] button not working

### ISSUE THREAD

**Issue by ghost** [TeamUltroid/Ultroid#394]
### What happened?

A bug happened!

Any button on .help command and others command will not working

Bellow i provided instance log from mogenius website

### Version

0.7

### Hosted On

Other

### Relevant logs output

```shell
┏┳┓╋┏┓╋╋╋╋┏┓┏┓
            ┃┃┣┓┃┗┳┳┳━╋╋┛┃
            ┃┃┃┗┫┏┫┏┫╋┃┃╋┃
            ┗━┻━┻━┻┛┗━┻┻━┛
      Visit @TheUltroid for updates!!
12/08/2022, 08:33:55 | pyUltLogs [INFO] : 
                    -----------------------------------
                            Starting Deployment
                    -----------------------------------
    
12/08/2022, 08:33:55 | pyUltLogs [INFO] : Python version - 3.10.2
12/08/2022, 08:33:55 | pyUltLogs [INFO] : py-Ultroid Version - 2022.08.30
12/08/2022, 08:33:55 | pyUltLogs [INFO] : Telethon Version - 1.25.1 [Layer: 146]
12/08/2022, 08:33:55 | pyUltLogs [INFO] : Ultroid Version - 0.7.1 [qovery | kubernetes]
12/08/2022, 08:33:55 | pyUltLogs [INFO] : Installing 'redis' for database.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
12/08/2022, 08:34:15 | pyUltLogs [INFO] : Connecting to Redis...
12/08/2022, 08:34:15 | pyUltLogs [INFO] : Connected to Redis Successfully!
12/08/2022, 08:34:22 | pyUltLogs [INFO] : Trying to login.
12/08/2022, 08:34:22 | pyUltLogs [INFO] : Logged in as ㅤㅤㅤ ㅤㅤㅤ
12/08/2022, 08:34:22 | pyUltLogs [INFO] : Trying to login.
12/08/2022, 08:34:24 | Telethon.client.users [INFO] : Phone migrated to 5
12/08/2022, 08:34:24 | Telethon.client.telegrambaseclient [INFO] : Reconnecting to new data center 5
12/08/2022, 08:34:26 | pyUltLogs [INFO] : Logged in as @DravorLand_Bot
12/08/2022, 08:34:31 | pyUltLogs [INFO] : Initialising...
12/08/2022, 08:34:32 | Telethon.network.mtprotosender [ERROR] : Request caused struct.error: required argument is not an integer: GetFullChatRequest(chat_id=InputPeerChat(chat_id=812146992))
12/08/2022, 08:34:32 | pyUltLogs [ERROR] : required argument is not an integer
Traceback (most recent call last):
  File "/pyUltroid/startup/funcs.py", line 262, in autopilot
    await ultroid_bot.get_permissions(int(channel), asst.me.username)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/chats.py", line 1365, in get_permissions
    chat = await self(functions.messages.GetFullChatRequest(entity))
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 32, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 71, in _call
    future = sender.send(request, ordered=ordered)
  File "/usr/local/lib/python3.10/site-packages/telethon/network/mtprotosender.py", line 202, in send
    state = RequestState(request)
  File "/usr/local/lib/python3.10/site-packages/telethon/network/requeststate.py", line 18, in __init__
    self.data = bytes(request)
  File "/usr/local/lib/python3.10/site-packages/telethon/tl/tlobject.py", line 190, in __bytes__
    return self._bytes()
  File "/usr/local/lib/python3.10/site-packages/telethon/tl/functions/messages.py", line 2374, in _bytes
    struct.pack('
struct.error: required argument is not an integer
12/08/2022, 08:34:32 | Telethon.client.uploads [INFO] : Uploading file of 235172 bytes in 2 chunks of 131072
12/08/2022, 08:34:33 | pyUltLogs [ERROR] : Cannot cast InputPeerChat to any kind of InputChannel.
Traceback (most recent call last):
  File "/pyUltroid/startup/funcs.py", line 310, in autopilot
    await ultroid_bot(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 32, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 47, in _call
    await r.resolve(self, utils)
  File "/usr/local/lib/python3.10/site-packages/telethon/tl/functions/channels.py", line 462, in resolve
    self.channel = utils.get_input_channel(await client.get_input_entity(self.channel))
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 263, in get_input_channel
    _raise_cast_fail(entity, 'InputChannel')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast InputPeerChat to any kind of InputChannel.
12/08/2022, 08:34:34 | pyUltLogs [INFO] : • Installing Official Plugins || Count : 80 •
12/08/2022, 08:34:57 | pyUltLogs [INFO] : Took 49s to start •ULTROID•
12/08/2022, 08:34:57 | pyUltLogs [INFO] : 
            ----------------------------------------------------------------------
                Ultroid has been deployed! Visit @TheUltroid for updates!!
            ----------------------------------------------------------------------
    
12/08/2022, 08:47:44 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 08:47:45 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 08:47:47 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 08:47:48 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 14:33:51 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 14:33:53 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 14:33:54 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 14:33:55 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 14:34:35 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 315, in on_plug_in_callback_query_handler
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 14:34:36 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 315, in on_plug_in_callback_query_handler
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 16:32:50 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 175, in help_func
    await ult.edit(text, buttons=page_num(count, key), link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 16:32:50 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 175, in help_func
    await ult.edit(text, buttons=page_num(count, key), link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 16:32:50 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 175, in help_func
    await ult.edit(text, buttons=page_num(count, key), link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 16:32:50 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 175, in help_func
    await ult.edit(text, buttons=page_num(count, key), link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:22:47 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:22:48 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:22:49 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 138, in setting
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:22:52 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 293, in _
    await e.edit(buttons=button, link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:22:54 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 293, in _
    await e.edit(buttons=button, link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:22:55 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 293, in _
    await e.edit(buttons=button, link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:22:55 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 293, in _
    await e.edit(buttons=button, link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:23:07 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 315, in on_plug_in_callback_query_handler
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:23:08 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 315, in on_plug_in_callback_query_handler
    await event.edit(
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:28:41 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 175, in help_func
    await ult.edit(text, buttons=page_num(count, key), link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
12/08/2022, 22:28:42 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/pyUltroid/_misc/_assistant.py", line 77, in wrapper
    await func(event)
  File "/plugins/_inline.py", line 175, in help_func
    await ult.edit(text, buttons=page_num(count, key), link_preview=False)
  File "/usr/local/lib/python3.10/site-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.10/site-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.10/site-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by Exekutori** [comment]
For someone works in private chats. If for you isn't working (as I see from your logs) you can use the buttons of the help only in the logger group that Ultroid has created for you.

Bye.
