### ISSUE TITLE
reverse command find right sauce but after that will show error

### ISSUE THREAD

**Issue by datfooldive** [TeamUltroid/Ultroid#401]
### What happened?

if i use `.reverse` command when sauce found its will throw a error

![IMG_20230113_190747](https://user-images.githubusercontent.com/110718021/212306221-48b8ecb9-478a-4ea0-b76c-04512bd01831.jpg)

but sauce still can find on deleted message but for me this is annoying

![Screenshot_20230113-190008_Nekogram](https://user-images.githubusercontent.com/110718021/212306238-6543b109-671c-4cee-be8d-781eee6c3bc1.png)

### Version

> 0.7

### Hosted On

Vps

### Relevant logs output

```shell
--------START ULTROID CRASH LOG--------
Date: 2023-01-13 10:59:42
Group: -1001836609557 My Ultroid Logs
Sender ID: 5366797695
Replied: True

Event Trigger:
.reverse

Traceback info:
Traceback (most recent call last):
  File "/root/workflows/private/userbot/Ultroid/pyUltroid/_misc/_decorators.py", line 113, in wrapp
    await dec(ult)
  File "/root/workflows/private/userbot/Ultroid/plugins/search.py", line 178, in reverse
    pth = await gi.download(args)
  File "/root/workflows/private/userbot/Ultroid/pyUltroid/fns/google_image.py", line 969, in download
    paths, errors = await self.download_executor(arguments)
  File "/root/workflows/private/userbot/Ultroid/pyUltroid/fns/google_image.py", line 1117, in download_executor
    items, errorCount, abs_path = self._get_all_items(
  File "/root/workflows/private/userbot/Ultroid/pyUltroid/fns/google_image.py", line 868, in _get_all_items
    image_objects = self._get_image_objects(page)
  File "/root/workflows/private/userbot/Ultroid/pyUltroid/fns/google_image.py", line 859, in _get_image_objects
    return json.loads(object_decode[:-15])[31][0][12][2]
TypeError: 'NoneType' object is not subscriptable


Error text:
'NoneType' object is not subscriptable

--------END ULTROID CRASH LOG--------


Last 5 commits:
Aditya: feat: fix up session gen
Devesh Pal: chore: fix chatbot and other minor issues.
Aditya: chore: update sessiongen to work with pyrogram 2.0
Aditya: chore: remove dead clone link from termux installer
CyrusXD: Merge pull request #380 from e3ris/patch-3
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by New-dev0** [comment]
@kyzsuukii it is fixed on dev branch and main will be updated with next upcoming update.
(which may take more than a month, not sure about that)

**Comment by datfooldive** [comment]
> @kyzsuukii it is fixed on dev branch and main will be updated with next upcoming update.
> (which may take more than a month, not sure about that)

dev branch is unstable??
