### ISSUE TITLE
[BUG REPORT] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gmankab** [TeamUltroid/Ultroid#410]
### Contact Details

t.me/UltroidSupportChat/126348

### What happened?

Ultroid Client Error: Forward this to @UltroidSupportChat

Py-Ultroid Version: 2023.02.20
Ultroid Version: 0.8
Telethon Version: 1.25.1
Hosted At: local

--------START ULTROID CRASH LOG--------
Date: 2023-04-03 05:44:06
Group: -1001953544474 My Ultroid Logs
Sender ID: 6105156610
Replied: False

Event Trigger:
.ytv https://youtu.be/mAFMJ1LnQu8

```
Traceback info:
Traceback (most recent call last):
  File "/home/gmanka/Desktop/Ultroid/pyUltroid/_misc/_decorators.py", line 112, in wrapp
    await dec(ult)
  File "/home/gmanka/Desktop/Ultroid/plugins/youtube.py", line 85, in download_from_youtube_
    await download_yt(xx, url, ytd)
  File "/home/gmanka/Desktop/Ultroid/pyUltroid/fns/ytdl.py", line 144, in download_yt
    attributes = await set_attributes(file)
  File "/home/gmanka/Desktop/Ultroid/pyUltroid/fns/tools.py", line 145, in set_attributes
    data = await metadata(file)
  File "/home/gmanka/Desktop/Ultroid/pyUltroid/fns/tools.py", line 122, in metadata
    _info = json.loads(out)["media"]["track"]
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Error text:
Expecting value: line 1 column 1 (char 0)

--------END ULTROID CRASH LOG--------

Last 5 commits:
Devesh Pal: Update Ultroid v0.8
Aditya: feat: fix up session gen
Devesh Pal: chore: fix chatbot and other minor issues.
Aditya: chore: update sessiongen to work with pyrogram 2.0
Aditya: chore: remove dead clone link from termux installer

hosted on my computer
<details>
  <summary>neofetch</summary>

  ![image](https://user-images.githubusercontent.com/73340745/229423700-ca0f63d0-fc0b-4ddf-9dc6-2a45eac28ad7.png)

</details>

### Version

> 0.7

### Hosted On

Other

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by amitkr-codes** [comment]
@gmankab apt install ffmpeg mediainfo -y

**Comment by gmankab** [comment]
> @gmankab apt install ffmpeg mediainfo -y

it helped, thanks

i think bot must check if ffmpeg and mediainfo are installed

and if they are not installed, bot must say it
