### ISSUE TITLE
Function Carbon Not Working

### ISSUE THREAD

**Issue by allixina** [TeamUltroid/Ultroid#413]
Py-Ultroid Version: 2023.02.20
Ultroid Version: 0.8
Telethon Version: 1.25.1
Hosted At: local

Event Trigger:
.carbon

Traceback info:
Traceback (most recent call last):
  File "/root/Ubot/Ultroid3/Ultroid/pyUltroid/_misc/_decorators.py", line 112, in wrapp
    await dec(ult)
  File "/root/Ubot/Ultroid3/Ultroid/plugins/beautify.py", line 41, in cr_bn
    code = a.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Error text:
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by Anekashastrahasta** [comment]
Fixed it in my pull request
