### ISSUE TITLE
[BUG REPORT] Bugs During Local Deploy

### ISSUE THREAD

**Issue by floramabel** [TeamUltroid/Ultroid#425]
### Contact Details

@Julie_Kane

### What happened?

I Got  few bugs when locally deploying ultroid... here have a look...

https://spaceb.in/api/v1/documents/QBpqlVWP/raw

Please Help me fix those 

### Version

0.5

### Hosted On

Vps

### Relevant logs output

```shell
08/27/2023, 10:10:17 | pyUltLogs [INFO] : 
                    -----------------------------------
                            Starting Deployment
                    -----------------------------------
    
08/27/2023, 10:10:17 | pyUltLogs [INFO] : Python version - 3.11.4
08/27/2023, 10:10:17 | pyUltLogs [INFO] : py-Ultroid Version - 2023.02.20
08/27/2023, 10:10:17 | pyUltLogs [INFO] : Telethon Version - 1.25.1 [Layer: 151]
08/27/2023, 10:10:17 | pyUltLogs [INFO] : Ultroid Version - 0.8 [local]
08/27/2023, 10:10:34 | pyUltLogs [INFO] : Connecting to Redis...
08/27/2023, 10:10:34 | pyUltLogs [INFO] : Connected to Redis Successfully!
08/27/2023, 10:10:36 | pyUltLogs [INFO] : Trying to login.
08/27/2023, 10:10:36 | pyUltLogs [INFO] : Trying to login.
08/27/2023, 10:10:38 | Telethon.client.users [INFO] : Phone migrated to 5
08/27/2023, 10:10:38 | Telethon.client.telegrambaseclient [INFO] : Reconnecting to new data center 5
08/27/2023, 10:10:41 | pyUltLogs [INFO] : Logged in as @Julie_Kane_bot
08/27/2023, 10:10:41 | pyUltLogs [INFO] : Starting up VcClient.
08/27/2023, 10:10:42 | pyUltLogs [CRITICAL] : String session expired.
08/27/2023, 10:10:42 | pyUltLogs [INFO] : While creating Client for VC.
08/27/2023, 10:10:42 | pyUltLogs [ERROR] : 'NoneType' object has no attribute 'bot'
Traceback (most recent call last):
  File "E:\Python\WPy64-31140\scripts\pyUltroid\startup\connections.py", line 83, in vc_connection
    return UltroidClient(
           ^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\scripts\pyUltroid\startup\BaseClient.py", line 50, in __init__
    self.run_in_loop(self.start_client(bot_token=bot_token))
  File "E:\Python\WPy64-31140\scripts\pyUltroid\startup\BaseClient.py", line 222, in run_in_loop
    return self.loop.run_until_complete(function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\scripts\pyUltroid\startup\BaseClient.py", line 88, in start_client
    if self.me.bot:
       ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'bot'
08/27/2023, 10:10:47 | pyUltLogs [INFO] : Initialising...
08/27/2023, 10:10:49 | pyUltLogs [INFO] : • Installing Official Plugins || Count : 79 •
08/27/2023, 10:10:59 | apscheduler.scheduler [INFO] : Adding job tentatively -- it will be properly scheduled when the scheduler starts
08/27/2023, 10:10:59 | apscheduler.scheduler [INFO] : Adding job tentatively -- it will be properly scheduled when the scheduler starts
08/27/2023, 10:10:59 | apscheduler.scheduler [INFO] : Added job "close_grp" to job store "default"
08/27/2023, 10:10:59 | apscheduler.scheduler [INFO] : Added job "open_grp" to job store "default"
08/27/2023, 10:10:59 | apscheduler.scheduler [INFO] : Scheduler started
08/27/2023, 10:11:06 | pyUltLogs [ERROR] : 'akinator' not installed.
08/27/2023, 10:11:07 | pyUltLogs [ERROR] : 'pytgcalls' not installed!
Skipping loading of VCBOT.
08/27/2023, 10:11:07 | pyUltLogs [INFO] : • Loading Plugins from Plugin Channel(s) •
08/27/2023, 10:11:07 | pyUltLogs [INFO] : •••• @ultroidplugins
08/27/2023, 10:11:08 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:09 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:09 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:10 | Telethon.client.telegrambaseclient [INFO] : Exporting auth for new borrowed sender in DcOption(id=2, ip_address='149.154.167.41', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, this_port_only=False, secret=None)
08/27/2023, 10:11:11 | pyUltLogs [INFO] : Ultroid - PLUGIN_CHANNEL - ERROR - addons\holi.py
08/27/2023, 10:11:11 | pyUltLogs [ERROR] : No module named 'pyUltroid.functions.google_image'
Traceback (most recent call last):
  File "E:\Python\WPy64-31140\scripts\pyUltroid\startup\funcs.py", line 425, in plug
    load_addons(plugin)
  File "E:\Python\WPy64-31140\scripts\pyUltroid\startup\utils.py", line 86, in load_addons
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Python\WPy64-31140\scripts\addons\holi.py", line 15, in <module>
    from pyUltroid.functions.google_image import googleimagesdownload
ModuleNotFoundError: No module named 'pyUltroid.functions.google_image'
08/27/2023, 10:11:12 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:12 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:14 | Telethon.client.telegrambaseclient [INFO] : Exporting auth for new borrowed sender in DcOption(id=1, ip_address='149.154.175.59', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, this_port_only=False, secret=None)
08/27/2023, 10:11:15 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:16 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:17 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:18 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:18 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:21 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:22 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:23 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:24 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:25 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:26 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:26 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:26 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:27 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:28 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:29 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:30 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:30 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:31 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:32 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:32 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:33 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:34 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:35 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:35 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:36 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:37 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:38 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:38 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:38 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:39 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:39 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:40 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:41 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:41 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:42 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:43 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:44 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:44 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:45 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:46 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:47 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:47 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:48 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:49 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:49 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:50 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:51 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:51 | Telethon.client.downloads [INFO] : File lives in another DC
08/27/2023, 10:11:52 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:53 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:54 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:54 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:55 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:56 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:56 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:57 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:58 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:59 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:11:59 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:00 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:01 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:01 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:02 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:03 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:04 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:04 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:05 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:06 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:07 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:08 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:08 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:09 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:10 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:11 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:12 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:13 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:13 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:14 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:15 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:16 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:17 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:17 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:18 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:19 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:20 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:22 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:22 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:23 | Telethon.client.downloads [INFO] : Starting direct file download in chunks of 131072 at 0, stride 131072
08/27/2023, 10:12:24 | pyUltLogs [ERROR] : list index out of range
Traceback (most recent call last):
  File "E:\Python\WPy64-31140\scripts\pyUltroid\fns\helper.py", line 279, in updater
    off_repo = Repo().remotes[0].config_reader.get("url").replace(".git", "")
               ~~~~~~~~~~~~~~^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\git\util.py", line 1090, in __getitem__
    return list.__getitem__(self, index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
08/27/2023, 10:12:25 | pyUltLogs [ERROR] : Cannot connect to host ultroid-api.vercel.app:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)')]
Traceback (most recent call last):
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\asyncio\base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\asyncio\base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\asyncio\sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\asyncio\sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python\WPy64-31140\scripts\pyUltroid\startup\funcs.py", line 445, in fetch_ann
    updts = await async_searcher(
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\scripts\pyUltroid\fns\helper.py", line 369, in async_searcher
    data = await method(url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\WPy64-31140\python-3.11.4.amd64\Lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host ultroid-api.vercel.app:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)')]
08/27/2023, 10:12:25 | apscheduler.scheduler [INFO] : Adding job tentatively -- it will be properly scheduled when the scheduler starts
08/27/2023, 10:12:25 | apscheduler.scheduler [INFO] : Added job "fetch_ann" to job store "default"
08/27/2023, 10:12:25 | apscheduler.scheduler [INFO] : Scheduler started
08/27/2023, 10:12:25 | pyUltLogs [INFO] : Took 2m:6s to start •ULTROID•
08/27/2023, 10:12:25 | pyUltLogs [INFO] : 
            ----------------------------------------------------------------------
                Ultroid has been deployed! Visit @TheUltroid for updates!!
            ----------------------------------------------------------------------
    
08/27/2023, 10:12:28 | Telethon.client.uploads [INFO] : Uploading file of 21105 bytes in 1 chunks of 131072
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by MrAnayDongre** [comment]
`AttributeError: 'NoneType' object has no attribute 'bot'` is the main issue here. It's trying to access the bot attribute of an object that is `None`. It's likely related to your bot token. Make sure you have provided the correct bot token for your Telegram bot.
