### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by deerwinter** [TeamUltroid/Ultroid#430]
### Contact Details

m64dep8sl@mozmail.com

### What happened?

Try to deploy it on vps,but when i run it it will throw 2 error.
[error1] string/string/en.yml report that special symbol  is not supported
[error2] the negative number group ID become positive in logs and report error 

### Version

> 0.7

### Hosted On

Vps

### Relevant logs output

```shell
Telethon.network.mtprotosender [ERROR] : Request caused struct.error: required argument is not an integer: GetFullChatRequest(chat_id=InputPeerChat(chat_id=!!!this one become positive instead of negative!!))
12/12/2023, 17:59:13 | pyUltLogs [ERROR] : required argument is not an integer
Traceback (most recent call last):
  File "/root/Ultroid/pyUltroid/startup/funcs.py", line 273, in autopilot
    await ultroid_bot.get_permissions(int(channel), asst.me.username)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/chats.py", line 1365, in get_permissions
    chat = await self(functions.messages.GetFullChatRequest(entity))
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 32, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 71, in _call
    future = sender.send(request, ordered=ordered)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 202, in send
    state = RequestState(request)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/requeststate.py", line 18, in __init__
    self.data = bytes(request)
  File "/usr/local/lib/python3.8/dist-packages/telethon/tl/tlobject.py", line 190, in __bytes__
    return self._bytes()
  File "/usr/local/lib/python3.8/dist-packages/telethon/tl/functions/messages.py", line 2410, in _bytes
    struct.pack('<q', self.chat_id),
struct.error: required argument is not an integer



symbols like 😂 be reported not supported.
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by deerwinter** [comment]
the menu from .help is not work too, 
press the [plugin]  [inline plugin] result in error report on vps

`12/12/2023, 18:30:40 | pyUltLogs [ERROR] : Cannot cast NoneType to any kind of Peer.
Traceback (most recent call last):
  File "/root/Ultroid/pyUltroid/_misc/_assistant.py", line 84, in wrapper
    await func(event)
  File "/root/Ultroid/plugins/_inline.py", line 293, in _
    await e.edit(buttons=button, link_preview=False)
  File "/usr/local/lib/python3.8/dist-packages/telethon/events/callbackquery.py", line 341, in edit
    return await self._client.edit_message(
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/messages.py", line 1227, in edit_message
    entity = await self.get_input_entity(entity)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 470, in get_input_entity
    peer = utils.get_peer(peer)
  File "/usr/local/lib/python3.8/dist-packages/telethon/utils.py", line 997, in get_peer
    _raise_cast_fail(peer, 'Peer')
  File "/usr/local/lib/python3.8/dist-packages/telethon/utils.py", line 138, in _raise_cast_fail
    raise TypeError('Cannot cast {} to any kind of {}.'.format(
TypeError: Cannot cast NoneType to any kind of Peer.
`

[addon] button ask for .setdb ADDONS True, after i set it , it will respond that value is set ,but click [addon] will still pop up the INFO.
