### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Adisdzaky1** [TeamUltroid/Ultroid#461]
### Contact Details

@Oficiallz

### What happened?

I am getting an error when running the script. I have set everything correctly but an error occurs.

![Screenshot_2024-10-26-20-43-11-22](https://github.com/user-attachments/assets/f2720d6e-6368-43dd-9416-33def67bad3f)

### Version

> 0.7

### Hosted On

Vps

### Relevant logs output

```shell
Using Telethon-Patch (v0.04b0) [188]
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/businezzrl/public_html/Ultroid/pyUltroid/__init__.py", line 24, in <module>
    from .configs import Var
  File "/home/businezzrl/public_html/Ultroid/pyUltroid/configs.py", line 20, in <module>
    class Var:
  File "/home/businezzrl/public_html/Ultroid/pyUltroid/configs.py", line 41, in Var
    LOG_CHANNEL = config("LOG_CHANNEL", default=0, cast=int)
  File "/home/businezzrl/public_html/Ultroid/venv/lib/python3.9/site-packages/decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
  File "/home/businezzrl/public_html/Ultroid/venv/lib/python3.9/site-packages/decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
  File "/home/businezzrl/public_html/Ultroid/venv/lib/python3.9/site-packages/decouple.py", line 101, in get
    return cast(value)
ValueError: invalid literal for int() with base 10: ''
```

### Acknowledgement

- [X] I have followed all of the above steps.

**Comment by amitkr-codes** [comment]
@Adisdzaky1 Check value of LOG_CHANNEL in your env file, it's not integer type

**Comment by RfHackingZone** [comment]
🤭🤭🤭😁😁
